"""initial schema

Revision ID: 47da95fe01a1
Revises: 
Create Date: 2026-05-08 23:37:27.153854

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '47da95fe01a1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('article_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('is_top', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('editorial_group', sa.String(length=32), nullable=False),
    sa.Column('rss_url', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('analyses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('common_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('by_source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('omissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('divergences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('has_full_text', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('cluster_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_articles_source_ext')
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE INDEX ix_articles_embedding_hnsw ON articles "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_clusters_centroid_hnsw ON clusters "
        "USING hnsw (centroid vector_cosine_ops)"
    )
    op.execute("CREATE INDEX ix_articles_published_at ON articles (published_at DESC)")
    op.execute("CREATE INDEX ix_articles_cluster_id ON articles (cluster_id)")
    op.execute("CREATE INDEX ix_clusters_display_date ON clusters (display_date DESC) WHERE is_top")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_clusters_display_date")
    op.execute("DROP INDEX IF EXISTS ix_articles_cluster_id")
    op.execute("DROP INDEX IF EXISTS ix_articles_published_at")
    op.execute("DROP INDEX IF EXISTS ix_clusters_centroid_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_articles_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('analyses')
    op.drop_table('sources')
    op.drop_table('runs')
    op.drop_table('clusters')
    # ### end Alembic commands ###
